### ISSUE TITLE
Identifying locale from URL fails when permalink is set to `false`

### ISSUE THREAD

**Issue by arkhi** [adamduncan/eleventy-plugin-i18n#10]
I was originally going to submit a PR, but since there are already 3 waiting, I decided to first open this issue.

Eleventy allows to [specify `permalink: false`](https://www.11ty.dev/docs/permalinks/#permalink-false) to not generate a page for specific templates.

This results in the error <q>TypeError: url.split is not a function</q> because `false.split` is problematic.

I think #5 actually solves this issue.

**Comment by arkhi** [comment]
:innocent: Duplicate of #4.

**Comment by adamduncan** [comment]
Thanks @arkhi. There's a bit of extra functionality covered in #4 that we're not quite 100% on.

I think likely we'll get in a dedicated `permalink: false` fix as a patch release. Thanks for reminding me.
