### ISSUE TITLE
Assets handling

### ISSUE THREAD

**Issue by vogloblinsky** [adamduncan/eleventy-plugin-i18n#16]
Hi,

Thanks for this great plugin.

How can we handle assets like css files for example ?

**Comment by adamduncan** [comment]
Hi @vogloblinsky. Can you please elaborate a little on what you mean by "handle assets"?

**Comment by vogloblinsky** [comment]
I have a site with two languages : fr & en
The rendered website is :
```
/en-en/index.html
/fr-fr/index.html
```
When i put a css file in my src folder, i cannot use it in my main template.

**Comment by adamduncan** [comment]
Hey @vogloblinsky — not sure where you got to on this one. Closing for now. Re-open if there are any issues 👍
